baseURL = 'https://aigic8.github.com/'
languageCode = 'en-us'
title = 'Aigic8'
theme = 'rusty-typewriter'


[params.rtwt]
  sidePane = true
  countPageItems = 7

[params.rtwt.home]
  showBio = true
  showAuthorImg = false
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = true
  taxonomies = ['tags']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = false
  showDetails = false
  showTableOfContents = true
  showAttachments = false
  showRelated = false
  countRelated = 0
